apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api-devel
spec:
  selector:
    matchLabels:
      app: wallet-api-devel
  replicas: 3
  template:
    metadata:
      labels:
        app: wallet-api-devel
    spec:
      containers:
      - name: wallet-api-devel
        image: nginx:latest #nanajanashia/argocd-app:1.2
        env:
        - name: SOURCE_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: source_bucket_name
              key: source_bucket_name
        - name: SERVICE_ACCOUNT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: service_account_email
              key: service_account_email
        - name: ENTRY_POINT
          valueFrom:
            configMapKeyRef:
              name: entry_point
              key: entry_point
        - name: MIN_INSTANCES
          valueFrom:
            configMapKeyRef:
              name: min_instances
              key: min_instances
        ports:
        - containerPort: 8080
