apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api-devel
spec:
  selector:
    matchLabels:
      app: wallet-api-devel
  replicas: 3
  template:
    metadata:
      labels:
        app: wallet-api-devel
    spec:
      containers:
      - name: wallet-api-devel
        image: nginx:latest #nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
