apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api-devel
  namespace: default
  labels:
    app: wallet-api-dev
spec:
  selector:
    matchLabels:
      app: wallet-api-devel
      tier: backend
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: wallet-api-devel
        tier: backend
    spec:
      containers:
      - name: wallet-api-devel
        image: nginx:latest
        ports:
        - containerPort: 8080
